package com.smartlogix.usuarios.model;

public enum TipoEvento {
    INTENTO_MODIFICAR_ADMIN_BASE,
    INTENTO_CAMBIAR_ROL_ADMIN,
    INTENTO_ELIMINAR_ADMIN_BASE,
    INTENTO_ACCESO_NO_AUTORIZADO,
    INTENTO_ACTUALIZAR_OTRO_USUARIO,
    LOGIN_FALLIDO,
    USUARIO_NO_ENCONTRADO
}
